### ISSUE TITLE
No  if __name__ == "__main__": statement

### ISSUE THREAD

**Issue by Omegalpha44** [Fritober/Eureka-Johan_Liu-CDOF4#6]
The code cannot be used as a library for now, since there is no  ``` if __name__ == "__main__": ``` statement.

proposed fix : 
```python
 if __name__ == "__main__":
    quiz = QuizGame(questions)
    quiz.run()
```

**Comment by Fritober** [comment]
Indeed, i forget to add this, thanks for ur help !
